version: "3.8"

services:

  application:

    image: springboot-api:v1

    container_name: springboot-api

    ports:
      - "8080:8080"

    depends_on:
      - mysql

    networks:
      - devops-network

  mysql:

    image: mysql:8

    container_name: mysql-db

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: devopsdb

    volumes:
      - mysql-data:/var/lib/mysql

    networks:
      - devops-network

volumes:

  mysql-data:

networks:

  devops-network:
