groups:

- name: infrastructure-alerts

  rules:

  - alert: HighCPUUsage

    expr: 100 - (avg by(instance)
      (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80

    for: 2m

    labels:
      severity: critical

    annotations:
      summary: High CPU Usage

  - alert: HighMemoryUsage

    expr: (
      (node_memory_MemTotal_bytes -
       node_memory_MemAvailable_bytes)
       /
       node_memory_MemTotal_bytes
    ) * 100 > 80

    for: 2m

    labels:
      severity: warning

  - alert: DiskSpaceLow

    expr: (
      node_filesystem_avail_bytes
      /
      node_filesystem_size_bytes
    ) * 100 < 20

    for: 5m

    labels:
      severity: critical
